/**:
  ros__parameters:
    frame_pub_rate: 25
    frame_read_pub: "/frame_read_pub"
    frame_pub: "/frame_pub"


/video_reader:
  ros__parameters:
    source_file: "/mnt/chengxiao/20240222-194919.mp4"
    source_camera_index: -1
    start_frame_number: -1
    end_frame_number: -1
    image_width: 1920
    image_height: 1080
    frame_internal_ms: 40.0

/master_node:
  ros__parameters:
    status_query_service: "status_query"
    process_frame_action: "master_node_process_frame"
    step_interval_ms: 10.0
    timeout_ms_send_to_downstream: 1000.0


/detector_in_node:
  ros__parameters:
    process_document_action: "detector_in_process_document_action"
    step_interval_ms: 10.0
    timeout_ms_send_to_downstream: 1000.0

/detector_node:
  ros__parameters:
    process_frame_action: "model_process_frame_action"
    step_interval_ms: 10.0
    pred_score_thr: 0.3


/detector_out_node:
  ros__parameters:
    process_document_action: "detector_out_process_document_action"
    process_detections_action: "detector_out_process_detections_action"
    step_interval_ms: 10.0
    timeout_ms_send_to_downstream: 1000.0