/**:
  ros__parameters:
    frame_pub_rate: 25
    frame_read_pub: "/frame_read_pub"
    frame_pub: "/frame_pub"


/video_reader:
  ros__parameters:
    # source_file: "/mnt/chengxiao/test.mp4"
    # source_file: "/mnt/chengxiao/20.22.7.164-2023-06-18-17-00-00-00.00.00.000-00.00.04.240.mp4"
    # source_file: "/media/ramdisk/20.22.6.30-2023-06-18-15-00-02_27908_28658-00.00.00.000-00.00.06.926.mp4"
    source_file: "/3d/chengxiao/data/passengerflow/0912_badcase_test/20.22.6.214-2023-12-01-12-00-03_1400_1410.mp4"
    # source_file: "/mnt/chengxiao/data/passengerflow/fairmot_train_230907/videos/20.22.7.164-2023-06-18-17-00-00.mp4"
    # orbbec_net_device_ip: 192.168.32.141
    orbbec_net_device_ip: 192.168.32.139
    # orbbec_net_device_ip: 192.168.32.135
    source_camera_index: -1
    start_frame_number: -1
    end_frame_number: -1
    image_width: 1920
    image_height: 1080
    frame_interval_ms: 40.0
    send_goal_retry_times: 5

/master_node:
  ros__parameters:
    status_query_service: "status_query"
    process_frame_action: "master_node_process_frame"
    step_interval_ms: 1.0
    timeout_ms_send_to_downstream: 10000.0
    buffer_size: 5
    send_goal_retry_times: 5

/detector_in_node:
  ros__parameters:
    process_document_action: "detector_in_process_document_action"
    step_interval_ms: 1.0
    timeout_ms_send_to_downstream: 10000.0
    buffer_size: 5
    send_goal_retry_times: 5

/detector_node:
  ros__parameters:
    process_frame_action: "model_process_frame_action"
    step_interval_ms: 1.0
    pred_score_thr: 0.3
    buffer_size: 5
    send_goal_retry_times: 5


/detector_out_node:
  ros__parameters:
    process_document_action: "detector_out_process_document_action"
    process_detections_action: "detector_out_process_detections_action"
    step_interval_ms: 1.0
    timeout_ms_send_to_downstream: 10000.0
    buffer_size: 5
    send_goal_retry_times: 5

/person_generator_node:
  ros__parameters:
    process_document_action: "person_generator_process_document_action"
    step_interval_ms: 1.0
    timeout_ms_send_to_downstream: 10000.0
    buffer_size: 5
    send_goal_retry_times: 5


/pose_detector_in_node:
  ros__parameters:
    process_document_action: "pose_detector_in_process_document_action"
    step_interval_ms: 1.0
    timeout_ms_send_to_downstream: 10000.0
    buffer_size: 5
    send_goal_retry_times: 5

/pose_detector_node:
  ros__parameters:
    process_detections_action: "model_process_detections_action"
    step_interval_ms: 1.0
    pred_score_thr: 0.3
    buffer_size: 5
    send_goal_retry_times: 5

/pose_detector_out_node:
  ros__parameters:
    process_document_action: "pose_detector_out_process_document_action"
    process_bodyposes_action: "pose_detector_out_process_bodyposes_action"
    step_interval_ms: 1.0
    timeout_ms_send_to_downstream: 10000.0
    buffer_size: 5
    send_goal_retry_times: 5


/tracker_in_node:
  ros__parameters:
    process_document_action: "tracker_in_process_document_action"
    step_interval_ms: 1.0
    timeout_ms_send_to_downstream: 10000.0
    buffer_size: 5
    send_goal_retry_times: 5

/tracker_node:
  ros__parameters:
    process_detections_action: "tracker_process_detections_action"
    step_interval_ms: 1.0
    buffer_size: 5
    send_goal_retry_times: 5

/tracker_out_node:
  ros__parameters:
    process_document_action: "tracker_out_process_document_action"
    process_track_targets_action: "tracker_out_process_track_targets_action"
    step_interval_ms: 1.0
    timeout_ms_send_to_downstream: 10000.0
    buffer_size: 5
    send_goal_retry_times: 5

/psg_count_node:
  ros__parameters:
    process_document_action: "psg_count_process_document_action"
    step_interval_ms: 1.0
    timeout_ms_send_to_downstream: 10000.0
    # passengerflow_config_path: "/media/ramdisk/20.22.6.30.json"
    passengerflow_config_path: "/3d/chengxiao/data/passengerflow/0912_badcase_test/psg_configs/20.22.6.214.json"
    # passengerflow_config_path: "/mnt/chengxiao/data/passengerflow/fairmot_train_230907/videos/20.22.7.164.json"
    buffer_size: 5
    send_goal_retry_times: 5
