[general]
version = 1

[[segment]]
  name = "ExampleSegment" # 可以是任意名称

  [[segment.mempool]]
    size = 168
    count = 10000

  [[segment.mempool]]
    size = 1064
    count = 5000

  [[segment.mempool]]
    size = 16424
    count = 1000

  [[segment.mempool]]
    size = 131112
    count = 200

  [[segment.mempool]]
    size = 524328
    count = 50

  [[segment.mempool]]
    size = 1048616
    count = 30

  [[segment.mempool]]
    size = 4194344
    count = 10

  # 添加一个新的内存池，适合大小超过 6220856 字节的块
  [[segment.mempool]]
    size = 6220864
    count = 5