# action for get detections by frame from detector model node
unique_identifier_msgs/UUID x_uid
redoxi_public_msgs/Control x_control
redoxi_public_msgs/Frame frame
---
redoxi_public_msgs/Detection[] detections
redoxi_public_msgs/ReturnResponse x_return
---
redoxi_public_msgs/FeedbackResponse x_feedback
